# @package _global_

defaults:
  - /data: ph14t_*x224x224_qwen_multiling
  - /datamodule: standard
  - /prompt: fixed_prompt
  - override /hydra/hydra_logging: none
  - override /hydra/job_logging: none
  - _self_

hydra:
  run:
    dir: .
  sweep:
    dir: .
  output_subdir: null

seed: 42

model:
  checkpoint_dir: ???

engine:
  model_dtype: auto
  training_args:
    do_train: false
    do_eval: false
    do_predict: true
    predict_with_generate: true
    predict_with_teacher_forcing: false
    per_device_eval_batch_size: 1
    report_to: none
    remove_unused_columns: false
    dataloader_num_workers: 6
    dataloader_persistent_workers: true
    disable_tqdm: false
    auto_output_dir: false
    output_dir: outputs/evaluation
    logging_steps: 15
  generation_config:
    max_new_tokens: 128
    do_sample: false

experiment:
  permutation: false
