training_args:
  num_train_epochs: 80
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  report_to: none
  remove_unused_columns: False
  ddp_find_unused_parameters: False
  output_dir: outputs/first_demo
  save_strategy: steps
  save_steps: 500
  save_total_limit: 1
  logging_steps: 50
  eval_strategy: "steps"
  eval_steps: 500
  learning_rate: 1e-4
  dataloader_num_workers: 6
  # generation_config: null
generation_config:
  max_new_tokens: 128
