training_args:
  num_train_epochs: 80
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  report_to: wandb
  remove_unused_columns: False
  ddp_find_unused_parameters: False
  save_strategy: steps
  save_steps: 4000
  save_total_limit: 1
  logging_steps: 50
  eval_strategy: "steps"
  eval_steps: 4000
  learning_rate: 1e-5
  dataloader_num_workers: 4
  auto_output_dir: True
  auto_output_root: outputs/demos_ft
  lr_scheduler_type: cosine
  # dataloader_persistent_workers: True
  # generation_config: null
generation_config: # NOTE: override the generation config in model config
  max_new_tokens: 128
