training_args:
  do_train: true
  do_predict: true
  num_train_epochs: 60
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 1
  report_to: wandb
  remove_unused_columns: False
  ddp_find_unused_parameters: True
  save_strategy: steps
  save_steps: 4000
  save_total_limit: 2
  logging_steps: 50
  eval_strategy: "steps"
  eval_steps: 4000
  load_best_model_at_end: True # ⭐ 关键
  metric_for_best_model: "eval_overall_weighted_bleu4" # ⭐ 用哪个 metric 判断最佳
  greater_is_better: True # ⭐ 这个非常重要
  learning_rate: 1e-4
  dataloader_num_workers: 6
  disable_tqdm: True
  auto_output_dir: False
  # auto_output_root: outputs/demos
  output_dir: outputs/test
  lr_scheduler_type: cosine
  # dataloader_prefetch_factor: 2
  dataloader_persistent_workers: True
  # generation_config: null
  dataloader_drop_last: true # NOTE: 最后一个batch负载有可能不均衡
  # group_by_length: false # 已经自定义了sampler， 这个参数没有用了
generation_config: # NOTE: override the generation config in model config
  max_new_tokens: 128

llm_dtype: auto
visual_backbone_dtype: auto
