training_args:
  num_train_epochs: 80
  per_device_eval_batch_size: 2
  report_to: none
  remove_unused_columns: False
  ddp_find_unused_parameters: False
  dataloader_num_workers: 6
  disable_tqdm: False
  auto_output_dir: False
  # auto_output_root: outputs/eval
  logging_steps: 50
  # dataloader_persistent_workers: True
  # generation_config: null
  output_dir: outputs/eval_qwen-1.7b-shuffle-1
generation_config: # NOTE: override the generation config in model config
  max_new_tokens: 128
