config:
  hidden_size: 1152
  video_soft_token_id: 6
  video_token_scale: 0.5
  llm_model_name_or_path: google/gemma-3-1b-it
  visual_backbone_type: pretrained
  visual_backbone_kwargs:
    ckpt_path: /root/projects/sign_langauge_visual_pretrain/outputs/info_nce_pretrain/2025-10-04_03-47-05/checkpoint-10500
  visual_adapter_type: temporal_shuffle
  visual_adapter_kwargs:
    input_hidden_size: 768
    output_hidden_size: 1152
    scale_factor: 2
    mlp_depth: 2
