config:
  hidden_size: 1152
  video_soft_token_id: 6
  video_token_scale: 0.5
  llm_model_name_or_path: google/gemma-3-1b-it
  visual_backbone_type: pretrained
  visual_backbone_kwargs:
    hidden_size: 768
    backbone_type: "dinov2-with-token-sampler"
    backbone_kwargs:
      id: "facebook/dinov2-with-registers-base"
      output_layer: -2
      num_extra_queries: 4
      num_heads: 12
      num_adapter_layers: 4
    ckpt_path: outputs/pretrained_ckpt_v0.1/checkpoint-10500
  visual_adapter_type: temporal_shuffle
  visual_adapter_kwargs:
    input_hidden_size: 768
    output_hidden_size: 1152
    scale_factor: 2
    mlp_depth: 2
