config:
  hidden_size: 2048
  video_soft_token_id: 151656
  video_token_scale: 2.0
  dsid_loss_weight: 0.0
  dsid_js_tau: null
  llm_model_name_or_path: Qwen/Qwen3-1.7B
  visual_backbone_type: dinov2
  visual_backbone_config:
    id: facebook/dinov2-with-registers-base
    output_layer: -1
  visual_adapter_type: dinoframe_cross_v2
  visual_adapter_kwargs:
    input_dim: 768
    output_dim: 2048
    temperature: 0.1
    spatial_window_radius: 3
    temporal_gate_init: -2 #sigmoid
