config:
  hidden_size: 5120
  video_soft_token_id: 151656
  video_token_scale: 0.125
  llm_model_name_or_path: Qwen/Qwen3-14B
  visual_backbone_type: dinov2
  visual_backbone_kwargs:
    id: facebook/dinov2-with-registers-base
    output_layer: -2
    enable_lora: False
  visual_adapter_type: token_sampler_v2
  visual_adapter_kwargs:
    hidden_size: 768
    target_hidden_size: 5120
    num_heads: 12
    num_extra_queries: 4
    num_layers_sampler: 2
    num_layers_connector: 1
    use_temporal_shuffle: True
    sampler_out_mlp_depth: 2
    mlp_ratio: 2.0
    proj_drop: 0.0
    attn_drop: 0.0
    drop_path: 0.0
    eps: 1e-6
