config:
  hidden_size: 2048
  video_soft_token_id: 151656
  video_token_scale: 1.0
  video_bidirectional_attention: true
  llm_model_name_or_path: Qwen/Qwen3-1.7B
  visual_backbone_type: dinov3
  visual_backbone_config:
    id: facebook/dinov3-vith16plus-pretrain-lvd1689m
    output_layer: -1
  visual_adapter_type: dinoframe_cross_v2_shuffle
  visual_adapter_kwargs:
    input_dim: 1280
    cls_input_dim: 1280
    output_dim: 2048
    temperature: 0.1
    spatial_window_radius: 3
    temporal_gate_init: -2 #sigmoid
