config:
  hidden_size: 2048
  video_soft_token_id: 151656
  video_token_scale: 1.0
  dsid_loss_weight: 1.0
  dsid_js_tau: 0.6919847726821899
  llm_model_name_or_path: Qwen/Qwen3-1.7B
  visual_backbone_type: c_radio_v4
  visual_backbone_config:
    id: nvidia/C-RADIOv4-SO400M
    output_layer: [-1]
  visual_adapter_type: dinoframe_cross_v2_shuffle
  visual_adapter_kwargs:
    input_dim: 1152
    cls_input_dim: 2304
    output_dim: 2048
    temperature: 0.1
    use_short_temporal_conv: false
