config:
  hidden_size: 2048
  video_soft_token_id: 151656
  video_token_scale: 2.0
  video_bidirectional_attention: true
  llm_model_name_or_path: Qwen/Qwen3-1.7B
  visual_backbone_type: c_radio_v4
  visual_backbone_config:
    id: nvidia/C-RADIOv4-SO400M
    output_layer: [-1, -2, -3, -4]
  visual_adapter_type: dinoframe_cross_v2_global
  visual_adapter_kwargs:
    input_dim: 1152
    cls_input_dim: 2304
    output_dim: 2048
    temperature: 0.1
    spatial_window_radius: 3
    temporal_gate_init: -2 #sigmoid
    semantic_hidden_dim: 512
    semantic_num_layers: 2
    semantic_num_heads: 8
    semantic_ffn_dim: 1024
    semantic_dropout: 0.1
    max_frames: 1024
    local_residual_gate_init: 0.0
