defaults:
  - model: base_ft_peft
  # - data: ph14t_*x224x224_gemmaslt_multiling
  - data: ph14t_*x224x224_gemmaslt
  - engine: base_engine_ft_peft
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none
  - _self_

hydra:
  run:
    dir: .
  sweep:
    dir: .
  output_subdir: null
