# @package _global_

defaults:
  - /model: base_model
  # - model: pretrained_encoder_model
  - /data: ph14t_*x224x224_qwen_multiling
  # - data: ph14t_*x224x224_qwen
  - /datamodule: standard
  - /peft: none
  - override /hydra/hydra_logging: none
  - override /hydra/job_logging: none
  - _self_

hydra:
  run:
    dir: .
  sweep:
    dir: .
  output_subdir: null

engine:
  dsid_scheduler:
    warmup_ratio: 0.1
    decay_ratio: 0.3
  training_args:
    do_train: true
    do_predict: true
    num_train_epochs: 35
    per_device_train_batch_size: 2
    per_device_eval_batch_size: 1
    report_to: wandb
    remove_unused_columns: False
    ddp_find_unused_parameters: True
    save_strategy: best
    save_steps: 4000
    save_total_limit: 1
    logging_steps: 50
    eval_strategy: "steps"
    eval_steps: 4000
    load_best_model_at_end: True
    metric_for_best_model: "eval_overall_weighted_bleu4"
    greater_is_better: True
    learning_rate: 1e-4
    dataloader_num_workers: 6
    disable_tqdm: True
    auto_output_dir: False
    output_dir: outputs/test
    lr_scheduler_type: cosine
    restore_callback_states_from_checkpoint: true
    dataloader_persistent_workers: True
    dataloader_drop_last: true
  generation_config:
    max_new_tokens: 128
    do_sample: false
    # num_beams: 4
    # early_stopping: true
    # length_penalty: 1.0
  metrics:
    xcomet_every_n_evaluations: -1

  llm_dtype: auto
  visual_backbone_dtype: auto
