# @package _global_

defaults:
  - base
  - override /datamodule: split_subset
  - _self_

datamodule:
  strategy:
    train_percentage: 40
    val_percentage: 50
    test_percentage: 50
    train_seed: 42
    val_seed: 42
    test_seed: 42

engine:
  training_args:
    do_predict: false
    num_train_epochs: 50
    report_to: none
    eval_strategy: steps
    eval_steps: 0.1 #every 1 epochs
    save_strategy: "no"
    load_best_model_at_end: false
    output_dir: outputs/quick_validation
