# @package _global_

defaults:
  - base
  - override /peft: qwen3-1.7b-llm-last4
  - _self_

hydra:
  run:
    dir: .
  sweep:
    dir: .
  output_subdir: null

engine:
  training_args:
    do_train: true
    do_predict: true
    num_train_epochs: 35
    per_device_train_batch_size: 2
    per_device_eval_batch_size: 1
    report_to: wandb
    remove_unused_columns: False
    ddp_find_unused_parameters: True
    save_strategy: best
    save_steps: 4000
    save_total_limit: 1
    logging_steps: 50
    eval_strategy: "steps"
    eval_steps: 4000
    load_best_model_at_end: True
    metric_for_best_model: "eval_overall_weighted_bleu4"
    greater_is_better: True
    learning_rate: 1e-4
    dataloader_num_workers: 6
    disable_tqdm: True
    auto_output_dir: False
    output_dir: outputs/test
    lr_scheduler_type: cosine
    restore_callback_states_from_checkpoint: true
    dataloader_persistent_workers: True
    dataloader_drop_last: true

  llm_dtype: auto
  visual_backbone_dtype: auto
peft:
  lora_config:
    r: 8
    lora_alpha: 16
    lora_dropout: 0.05
    bias: "none"
    target_modules:
      - "q_proj"
      - "v_proj"
